[project]
name = "keras-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=0.4.1",
    "pandas>=3.0.0",
    "tensorflow>=2.20.0",
]
